Sifchain/sifchain-ui

.github/workflows/pinata-build-deploy-ui.yml

Activate abiility to set mainnet DNS via Cloudflare

.github/workflow/pinata: activate set mainnet dns

---

ui/e2e/pages/KeplrNotificationPopup.js

This has been causing mega flakiness in our testing suite when every test accidentally fails and we need to run them again

Fix issue with keplr not being waited on

---

ui/app/src/views/SinglePool.vue

Fixes https://github.com/sifchain/issues/492

Fix net gain/loss tooltip

---

.github/workflows/pinata-build-deploy-ui.yml

workflow/pinata: temp remove tests

---

ui/core/src/config/getEnv.ts

core/getEnv: new pinata gateway

---

ui/app/src/views/RewardsPage.vue

mccal and andrew are going to kill me

rewardsPage.vue: copy update

---

ui/core/src/clients/wallets/KeplrWalletProvider.ts
ui/core/src/clients/wallets/types.ts
ui/core/src/generated/proto/sifnode/tokenregistry/v1/types.ts
ui/core/src/services/IBCService/IBCService.ts
ui/core/src/services/IBCService/tokenRegistry.ts
ui/core/src/services/WalletService/WalletService.ts

* Update proto types for nativedexclient
* Update tokenregistry to use nativedexclient

Update tokenRegistry to use nativedexclient

---

ui/app/src/views/BalancePage/Export/Select.tsx
ui/core/src/usecases/wallet/eth.ts

1. Fix chainid subscription being removed
2. Fix gas validation error not showing if you don't have ceth balance at all

Fix eth exports

---

ui/app/src/hooks/useToken.ts
ui/app/src/views/PoolPage/PoolPage.tsx

Fixed decomissioned pools not showing their assets properly

Show decomissioned pool assets

---

.github/workflows/pinata-build-deploy-ui.yml
.github/workflows/vercel-deploy-ui.yml
ui/app/package.json
ui/app/src/main.ts
ui/yarn.lock

- Remove Docker fetch on compile.
- Fetch JSON ABIs from Sifnode Repo.
- Set app environment variables at compile time: SHA, APP_VERSION (from package.json).

workflow: pinata

---

.github/workflows/pinata-build-deploy-ui.yml
.github/workflows/vercel-deploy-ui.yml

This shouldn't matter since ABI uses same methods and address is in the config. If testnet, use `sifchain-1` contract since that's manually promoted to mainnet. All else gets devnet contract.

Fix Slack Notification - Hardcode contract location

---

.github/workflows/pinata-build-deploy-ui.yml
.github/workflows/vercel-deploy-ui.yml
ui/app/CHANGELOG.md

Local workflow development does not allow for artifact upload so its a bit noisy.

Fix typo in Environment name

---

ui/core/src/services/ClpService/ClpService.ts
ui/core/src/services/IBCService/IBCService.ts
ui/core/src/services/index.ts
ui/scripts/generate-ibc-denoms.mjs

Update logging to pair whitelisted interchain connections, channels, and chain id's in ts-relayer format

Update Logging to Enable Direct Devops Relayer Implementation

---

.github/workflows/pinata-build-deploy-ui.yml

- Enable stuff on develop_pinata
- Fix the conditional

Fix build notifs for non-dev builds

---

ui/app/src/store/modules/accounts.ts

Check balances a LOT less for external chains.

---

ui/app/src/views/RewardsPage/components/ClaimRewardsModal.tsx

it's showing this:
I can't figure out why tonight so I'm just getting rid of it if it's glitched. Will show this if the amount is glitched:

Fix: the rewards less amount if claimed today is wrong if youve claimed before

---

ui/app/src/views/PoolPage/children/AddLiquidity/useAddLiquidityData.ts
ui/core/src/usecases/clp/calculators/reactiveAddLiquidityCalculator.ts

Clicking 'max' actually didn't work 😬 
PRing because add liquidity code is so sensitive

Fix add liquidity calculator balance

---

ui/app/package.json
ui/app/src/views/RewardsPage/components/RewardSection.tsx

When CF refuses to update build this will allow us to promote a testnet build for a sec

Do not show claimable rewards warning on dex.sif

---

ui/app/package.json
ui/app/src/hooks/useAsyncData.ts
ui/app/src/hooks/useAsyncDataCached.ts
ui/core/src/usecases/clp/syncPools.ts

- Fix getLiquidityProvider going twice, limit calls to it to 3 concurrent

hotfix: do not call getLiquidityProvider twice, max 3 concurrency'

---

.github/workflows/core.yml
codecov.yml

test: 💍 enforce the coverage action to run even when test fails

---

ui/app/CHANGELOG.md
ui/app/package.json
ui/app/src/components/TokenIcon.tsx
ui/core/src/config/networks/ethereum/assets.ethereum.mainnet.json
ui/core/src/config/networks/sifchain/assets.sifchain.mainnet.ts
ui/core/src/entities/Asset.ts

* Enabled 
* UST - Terra USD
* FRAX - Frax
* FXS - Frax Share
* ZCX - Unizen
* DON - Don-key
* METIS - Metis Token
* KFT - Knit Finance
* ZCN - 0chain
* SAITO - SAITO
* DFYN - DFYN Token
* DNXC - DinoX Coin
* ERN - @EthernityChain $ERN Token
* POLS - PolkastarterToken
* AXS - Axie Infinity Shard
* MATIC - Matic Token
* TOKE - Tokemak

Hotfix / Add Ethereum Tokens

---

ui/app/package.json
ui/app/src/store/modules/accounts.ts

fix hasLoadedBalances

---

ui/app/index.html

This reverts commit dcec3ce8aef603cdbfa5d66609e787c973cea2e2.

Revert "Add carrd.co redirect to clientside"

---

ui/app/CHANGELOG.md
ui/app/package.json
ui/core/scripts/getTopErcTokens.js
ui/core/src/config/networks/ethereum/assets.ethereum.mainnet.json
ui/core/src/config/networks/sifchain/assets.sifchain.mainnet.ts

* Enabled
* BTSG - BitSong
* QUICK - QuickSwap
* LDO - Lido DAO
* RAIL - Railgun
* POND - Marlin 
* DINO - DinoSwap
* UFO - UFO Gaming

Hotfix: ERC20 Additions 10/01/2021

---

ui/app/src/views/BalancePage/BalanceRow.tsx

https://github.com/Sifchain/issues/issues/851

Disable import/export on balances when a connection is under maintenance

---

ui/core/src/clients/bridges/IBCBridge/IBCBridge.ts
ui/core/src/clients/wallets/cosmos/KeplrWalletProvider.ts
ui/core/src/services/SifService/parseTxFailure.ts

Protobufs and no ledger ibc imports

---

ui/app/src/components/TokenNetworkIcon/TokenNetworkIcon.tsx
ui/app/src/componentsLegacy/NavSidePanel/NavMoreMenu.tsx
ui/app/src/componentsLegacy/NavSidePanel/NavSidePanel.tsx
ui/app/src/router/index.ts
ui/app/src/store/modules/export.ts
ui/app/src/store/modules/flags.ts
ui/app/src/views/BalancePage/Import/Select.tsx
ui/app/src/views/RewardsCalculatorPage/RewardsCalculatorPage.tsx
ui/app/src/views/RewardsCalculatorPage/components/RewardsCalculator/RewardsCalculator.tsx
ui/app/src/views/RewardsCalculatorPage/components/RewardsCalculator/index.ts
ui/app/src/views/RewardsCalculatorPage/hooks.ts
ui/app/src/views/RewardsPage/components/RewardSection.tsx
ui/app/tailwind.config.js
ui/core/src/config/chains/iris/iris-testnet.ts
ui/core/src/services/IBCService/IBCService.ts
ui/yarn.lock

https://app.zenhub.com/workspaces/sifchain-603ed608675da3001744d736/issues/sifchain/issues/1008

[feature] WIP: rewards calculator

---

ui/app/src/views/RewardsCalculatorPage/components/RewardsCalculator/RewardsCalculator.tsx

closes #409
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1201832881092167

fix(rewards calculator): sanitize inputs and clip overflow content

---

ui/core/package.json
ui/yarn.lock

hotfix: lock sifchain/core dependecy on web3js

---

ui/app/src/views/SwapPage/SwapPage.tsx

ui: sanitize swap modal's SlippageTolerance onChange handler

---

.github/workflows/ci-docker-image-pipeline.yaml

Added Curl Call to the Forble API in the Github Actions pipeline. This is to make it automatically publish new UI tags to the forble dex that is running causing it to update to the latest.

Auto Forble Tag Update with API Call.

---

.github/workflows/ci-docker-image-pipeline.yaml

Updating Curl Update for Master

---

ui/core/package.json

Looks like actual code coverage for tested files is closer to 60%, but should get this in to develop

Add code coverage flags

---

.github/workflows/pinata-build-deploy-ui.yml

domains are pointed to Vercel now so these are no longer needed

ci: fix pinata build & remove setting of DNS

---

core/src/entities/Pool.ts

Reverts Sifchain/sifchain-ui#504
actually caused some other issue, need to investigate

Revert "fix: flaky references"

---

app/src/business/providers/SifchainClientsProvider.tsx

for easier usage with `useMutation`

chore: add get or init clients function

---

app/src/views/PoolPage/PoolItem.tsx
app/src/views/PoolPage/PoolPage.tsx

grey out & disable button for orther unlock requests

fix: only show loading spinner for active unlock

---

core/src/clients/sifchain/fees.ts

this is more aligned with our current default

chore: adjust default gas fee

---

app/src/domains/clp/queries/params.ts
app/src/hooks/usePoolStats.ts
app/src/views/PoolPage/PoolItem.tsx
app/src/views/PoolPage/PoolPage.tsx
app/src/views/PoolPage/usePoolPageData.tsx
app/src/views/StatsPage/StatsPage.tsx
app/src/views/StatsPage/useStatsPageData.ts

feat: update pool pool stats with on chain rewards

---

app/src/views/PoolPage/PoolItem.tsx
app/src/views/PoolPage/usePoolPageData.tsx
app/src/views/StatsPage/StatsPage.tsx
app/src/views/StatsPage/useStatsPageData.ts

fix: copy and pool tvl

---

app/src/business/providers/SifchainClientsProvider.tsx
core/src/clients/native/NativeAminoTypes.ts
core/src/clients/sifchain/signingClient.ts
wallet-keplr/src/KeplrWalletProvider.ts

https://docs.keplr.app/api/cosmjs.html#types-of-offline-signers

feat: use `getOfflineSignerAuto` for ledger support

---

app/src/business/providers/SifchainClientsProvider.tsx
core/src/clients/sifchain/client.spec.ts
core/src/clients/sifchain/index.ts
core/src/clients/sifchain/signingStargateClient.ts

will allow us to easily add convenient methods later on,
while keeping compatibility with base cosmos client

refactor: signing client to class

---

package.json

Increment version for the docker build.

increment version

---

app/src/domains/clp/queries/params.ts
app/src/domains/tokenRegistry/queries/tokenRegistry.ts
app/src/main.ts

might means the user will need to do a browser refresh sometime to get the latest data
fix Sifchain/issues#1512

chore: more aggressive caching

---

app/src/main.ts

https://github.com/vitejs/vite/issues/1973

fix: process undefined from vite build

---

app/src/views/PoolPage/children/AddLiquidity/AddLiquidity.tsx

ui: add warning on Add Liquidity confirmation to mention unbonding period

---

app/src/business/usecases/clp/addLiquidity.ts
app/src/hooks/useTransactionDetails.ts
app/src/utils/runCatching.ts
core/src/clients/native/index.ts

fix: add liquidity error handling

---

core/src/config/chains/terra/terra-mainnet.ts
core/src/config/chains/terra/terra-testnet.ts

fix Sifchain/issues#1393
fix Sifchain/issues#1423

chore: re-enable terra

---

app/src/views/PoolPage/PoolPage.tsx
app/src/views/PoolPage/usePoolPageData.tsx

resulting in spinner showing the 2 times

fix: loading does not wait for current reward period

---

app/CHANGELOG.md
app/package.json
package.json

* fix terra station integration

[prerelease] release/2.6.16

---

app/src/domains/clp/mutation/liquidity.ts
app/src/store/modules/flags.ts
app/src/views/PoolPage/PoolItem.tsx
app/src/views/PoolPage/PoolPage.tsx
core/proto/sifnode/clp/v1/params.proto
core/proto/sifnode/clp/v1/querier.proto
core/proto/sifnode/clp/v1/tx.proto
core/proto/sifnode/clp/v1/types.proto
core/proto/sifnode/tokenregistry/v1/types.proto
core/src/generated/proto/cosmos/base/query/v1beta1/pagination.ts
core/src/generated/proto/google/protobuf/descriptor.ts
core/src/generated/proto/sifnode/clp/v1/params.ts
core/src/generated/proto/sifnode/clp/v1/querier.ts
core/src/generated/proto/sifnode/clp/v1/tx.ts
core/src/generated/proto/sifnode/clp/v1/types.ts
core/src/generated/proto/sifnode/oracle/v1/types.ts
core/src/generated/proto/sifnode/tokenregistry/v1/types.ts

feat: liquidity unlock cancellation

---

app/package.json
app/src/components/VotingModal/VotingModal.tsx
core/src/clients/chains/GravityChain.ts
core/src/clients/chains/index.ts
core/src/clients/index.ts
core/src/config/chains/gravity/gravity-mainnet.ts
core/src/config/chains/gravity/index.ts
core/src/config/chains/index.ts
core/src/config/networks/sifchain/assets.sifchain.devnet.json
core/src/config/networks/sifchain/assets.sifchain.mainnet.json
core/src/config/networks/sifchain/assets.sifchain.testnet.json
core/src/entities/Network.ts

Adding: Gravity-Bridge Configs

Adding: Gravity-Bridge Configs

---

app/src/hooks/useTransactionDetails.ts
core/src/entities/Errors.ts
core/src/utils/parseTxFailure.ts
wallet-keplr/src/KeplrWalletProvider.ts

feat: liquidity protection error handling

---

app/src/components/Toggle/Toggle.tsx
app/src/views/PoolPage/PoolPage.tsx

feat: view toggle for small pools

---

app/package.json
app/src/hooks/usePoolStats.ts
package.json

Reverts Sifchain/sifchain-ui#717

Revert "hotfix: multiply poolApr for display"

---

app/src/views/PoolPage/children/AddLiquidity/AddLiquidity.tsx
app/src/views/PoolPage/children/AddLiquidity/RiskWarning.tsx

This reverts commit e6cd1846aa43d77b4efe6c2c7fa5b491708aa2ae.

Revert "feat: margin disclaimer when adding liquidity"

---

app/src/views/PoolPage/children/AddLiquidity/AddLiquidity.tsx
app/src/views/PoolPage/children/AddLiquidity/RiskWarning.tsx

Reverts Sifchain/sifchain-ui#746

Revert "Revert "feat: margin disclaimer when adding liquidity""

---

app/package.json
app/src/store/modules/flags.ts
package.json

* Remote flags api integration
* disable ETH imports & export based on remote flag `DISABLE_ETH_BRIDGE`

[staging] release 2.10.1 rc

---

app/CHANGELOG.md
app/src/utils/prettyNumber.ts
app/src/views/PoolPage/PoolItem.tsx
app/src/views/StatsPage/StatsPage.tsx
app/src/views/StatsPage/useStatsPageData.ts

* dcacf893 prettyNumberMinMax for Margin APR in Pool nad Pool Stats pages
* 8b938002 add margin apr to pool stats

chore: add margin apr to pool stats page + using prettyNumber in both pool and pool stats page

---

app/package.json
app/src/components/Button/_CallToAction.tsx
app/src/components/Button/_CallToActionSecondary.tsx
app/src/components/Button/_Inline.tsx
app/src/store/modules/flags.ts
app/src/views/PoolPage/PoolPage.tsx
package.json

* reenable actions
* conditionally hide atom pool based on remote flag

[staging] 2.11.4 

---

app/package.json
app/src/components/Button/_CallToAction.tsx
app/src/components/Button/_CallToActionSecondary.tsx
app/src/components/Button/_Inline.tsx
app/src/store/modules/flags.ts
app/src/views/PoolPage/PoolPage.tsx
package.json

* re-enable actions
* temporarily hide ROWAN/ATOM pool based on remote flag

[release] 2.11.4

---

app/src/business/calculators/swapCalculatorPMTP.ts
app/src/domains/clp/queries/params.ts
app/src/views/SwapPage/SwapPage.tsx
app/src/views/SwapPage/useSwapPageData.ts

feature: validate swap input against current liquidity protection

---

app/package.json
app/src/components/Button/_CallToAction.tsx
app/src/components/Button/_CallToActionSecondary.tsx
app/src/components/Button/_Inline.tsx
app/src/store/modules/flags.ts
app/src/views/PoolPage/PoolPage.tsx
package.json

* validate ROWAN swaps against `current liquidity protection threshold`

[staging] /2.12.0

---

app/package.json
app/src/views/PoolPage/usePoolPageData.tsx
app/src/views/StatsPage/StatsPage.tsx
core/src/clients/sifchain/fees.ts
package.json

* rename `'Margin APR'` columns to `'Margin APY'`

[release] 2.12.8

---

app/CHANGELOG.md
app/package.json
app/src/business/usecases/clp/syncPools.ts
core/proto/sifnode/clp/v1/params.proto
core/proto/sifnode/clp/v1/querier.proto
core/proto/sifnode/clp/v1/tx.proto
core/src/config/networks/ethereum/assets.ethereum.devnet.json
core/src/config/networks/ethereum/assets.ethereum.localnet.json
core/src/config/networks/ethereum/assets.ethereum.testnet.json
core/src/config/networks/sifchain/config.devnet.json
core/src/config/networks/sifchain/config.localnet.json
core/src/config/networks/sifchain/config.staging.json
core/src/config/networks/sifchain/config.tempnet.json
core/src/config/networks/sifchain/config.testnet.json
core/src/generated/proto/sifnode/clp/v1/params.ts
core/src/generated/proto/sifnode/clp/v1/querier.ts
core/src/generated/proto/sifnode/clp/v1/tx.ts
package.json
yarn.lock

* handle dynamic swapFeeRate
* update peggy contracts for testnet (goerli)

[release] v2.14.1 production

---

.github/workflows/ci-docker-image-pipeline.yaml
app/package.json
package.json

* testnet release 2.14.10
* ci: 🎡 disable forbole job

Chore/bump version (#832)

---

app/package.json
app/src/components/NavSidePanel/NavSidePanel.tsx

Make old margin link inactive and greyed out

Make margin link inactive
